name: ManualDeltaDeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: test-build

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'minor-build-testing') && !contains(github.event.head_commit.message, 'next-build') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Running on branch
      run: echo ref ${{ github.event.inputs.branch }}
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        # Fetch all history commit
        fetch-depth: 0
    - uses: sfdx-actions/setup-sfdx@v1
      with:
        sfdx-auth-url: ${{ secrets.AUTH_SECRET }}

    - name: Install SFDX Git Delta
      run: |
        echo 'y' | sfdx plugins:install sfdx-git-delta

    - name: Generate package.xml
      run: |
        #Generate package.xml between the current branch & 
        sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output .
        echo "--- package.xml generated with added and modified metadata ---"
        cat package/package.xml

    - name: Deployement to PROD
      run: |
        sfdx force:source:deploy -x package/package.xml
